# Generated by Django 4.1.2 on 2022-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('listeners', models.BigIntegerField()),
                ('mbid', models.CharField(max_length=36)),
                ('url', models.CharField(max_length=50)),
                ('streamable', models.CharField(max_length=25)),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
