# Generated by Django 4.1.2 on 2022-12-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('issueDate', models.DateField(blank=True)),
                ('credentialID', models.CharField(blank=True, max_length=100, null=True)),
                ('credentialURL', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('fieldOfStudy', models.CharField(blank=True, max_length=100)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('current', models.BooleanField(blank=True, default=False)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('employmentType', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(blank=True, default=False)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Honors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'honors',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('name', models.CharField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=35)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('skills', models.ManyToManyField(blank=True, to='api.skill')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('socialmedia', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phoneNumber', models.CharField(blank=True, max_length=30)),
                ('currentEducation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.education')),
                ('currentJob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('listeners', models.BigIntegerField(blank=True)),
                ('mbid', models.CharField(blank=True, max_length=36)),
                ('url', models.CharField(blank=True, max_length=50, unique=True)),
                ('streamable', models.CharField(blank=True, max_length=25)),
                ('image_url', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('playcount', models.BigIntegerField(blank=True, null=True)),
                ('myplaycount', models.BigIntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='api.genres')),
            ],
            options={
                'db_table': 'artist',
            },
        ),
    ]
