# Generated by Django 4.1.2 on 2022-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
