# Generated by Django 4.1.2 on 2022-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='myplaycount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
